### 인터뷰 등록
POST http://localhost:8080/v1/applicant/1/interview
Authorization: eyJraWQiOiJrZXkyIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MUBuYXZlci5jb20iLCJpYXQiOjE3MTgzNDk5NDEsImV4cCI6MTcxODM3MTU0MX0.bd-f9hJnqfxigaNh1lptbL04Z8rFEkpe9PUImVpdkdU
Content-Type: application/json

{
  "interviewerId": 1,
  "interviewDate": "2024-07-15 12:30",
  "interviewRequestStatus": "INTERVIEW_REQUESTED"
}

### 인터뷰 등록
POST http://localhost:8080/v1/applicant/1/interview
Authorization: eyJraWQiOiJrZXkyIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiJ0ZXN0MUBuYXZlci5jb20iLCJpYXQiOjE3MTgzNDk5NDEsImV4cCI6MTcxODM3MTU0MX0.bd-f9hJnqfxigaNh1lptbL04Z8rFEkpe9PUImVpdkdU
Content-Type: application/json

{
  "interviewerId": 1,
  "interviewDate": "2024-07-15 12:30",
  "interviewRequestStatus": "INTERVIEW_CONFIRMATION_REQUESTED"
}


### 인터뷰 조회
GET http://localhost:8080/v1/applicant/1/interview

### 날짜로 인터뷰 조회
GET http://localhost:8080/v1/applicant/interview?date=2024-07-10

